apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  hostNetwork: true
  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: true
    kubernetesAttributes:
      enabled: true
    kubeletMetrics:
      enabled: true
    hostMetrics:
      enabled: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      debug:
        verbosity: detailed
      otlphttp:
        endpoint: http://victoria-metrics-victoria-metrics-single-server.vm.cluster.svc.local:8428/opentelemetry/api/v1/push
    service:
      pipelines:
        metrics:
          receivers: [ otlp ]
          exporters: [ otlphttp ]
