apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: soft-serve-deployment
  namespace: soft-serve
  labels:
    app: soft-serve
spec:
  selector:
    matchLabels:
      app: soft-serve
  serviceName: soft-serve      
  template:
    metadata:
      labels:
        app: soft-serve
    spec:
      volumes:
      - name: git-repo-data
        persistentVolumeClaim:
          claimName: soft-serve-pvc
      containers:
        - name: soft-serve
          image: docker.io/charmcli/soft-serve:latest
          ports:
          - containerPort: 23231
          env:
          - name: SOFT_SERVE_PORT
            value: '23231'
          - name: SOFT_SERVE_BIND_ADDRESS
            value: '0.0.0.0'
          volumeMounts:
          - name: git-repo-data
            mountPath: /soft-serve              
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: soft-serve-pvc
    namespace: soft-serve
spec:
    resources:
        requests:
            storage: 100Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path-hdd
---
apiVersion: v1
kind: Service
metadata:
  name: soft-serve
  namespace: soft-serve
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: soft-serve
  ports:
    - name: ssh
      protocol: TCP
      port: 22 
      targetPort: 23231
      nodePort: 33333
