apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nextcloud-metrics
    app.kubernetes.io/name: nextcloud-metrics
  name: nextcloud-metrics
  namespace: nextcloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nextcloud-metrics
      app.kubernetes.io/name: nextcloud-metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nextcloud-metrics
        app.kubernetes.io/name: nextcloud-metrics
    spec:
      containers:
      - env:
        - name: NEXTCLOUD_AUTH_TOKEN
          value: <path:kv/data/nextcloud#serverinfotoken>
        - name: NEXTCLOUD_SERVER
          value: http://nextcloud.nextcloud.svc.cluster.local:8080
        - name: NEXTCLOUD_TIMEOUT
          value: 5s
        - name: NEXTCLOUD_TLS_SKIP_VERIFY
          value: "false"
        image: xperimental/nextcloud-exporter:0.6.1
        imagePullPolicy: IfNotPresent
        name: metrics-exporter
        ports:
        - containerPort: 9205
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-metrics
  namespace: nextcloud
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9205
    protocol: TCP
    targetPort: 9205
  selector:
    app.kubernetes.io/instance: nextcloud-metrics
    app.kubernetes.io/name: nextcloud-metrics
  type: ClusterIP
