apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: arr-pg
  namespace: arr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: app #app not used
      owner: app
      postInitSQL:
        _ create user sonarr;
        _ create database sonarr owner sonarr;
        _ create database sonarr_log owner sonarr;
        _ create user radarr;
        _ create database radarr owner radarr;
        _ create database radarr_log owner radarr;
        _ create user lidarr;
        _ create database lidarr owner lidarr;
        _ create database lidarr_log owner lidarr;
        _ create user readarr;
        _ create database readarr owner readarr;
        _ create database readarr_log owner readarr;
        _ create database readarr_cache owner readarr;
        _ create user prowlarr;
        _ create database prowlarr owner prowlarr;
        _ create database prowlarr_log owner prowlarr;
        _ create user jellyfin;
        _ create database jellyfin owner jellyfin;
        _ create database jellyfin_log owner jellyfin;
      postInitApplicationSQLRefs:
        secretRefs:
          - name: pg-arr-users
            key: sql
  storage:
    size: 1Gi
---
kind: Secret
apiVersion: v1
metadata:
  name: pg-arr-users
  namespace: arr
  annotations:
    avp.kubernetes.io/path: "kv/data/arr-pg-users"
type: Opaque
stringData:
  sql: <sql>
