apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: arr-pg
  namespace: arr
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      owner: app
      postInitSQL:
        - create user sonarr;
        - create database sonarr owner sonarr;
        - create database sonarr_log owner sonarr;
        - create user radarr;
        - create database radarr owner radarr;
        - create database radarr_log owner radarr;
        - create user lidarr;
        - create database lidarr owner lidarr;
        - create database lidarr_log owner lidarr;
        - create user readarr;
        - create database readarr owner readarr;
        - create database readarr_log owner readarr;
        - create database readarr_cache owner readarr;
        - create user prowlarr;
        - create database prowlarr owner prowlarr;
        - create database prowlarr_log owner prowlarr;
        - create user jellyfin;
        - create database jellyfin owner jellyfin;
        - create database jellyfin_log owner jellyfin;
      postInitApplicationSQLRefs:
        secretRefs:
          - name: pg-arr-users
            key: sql
  storage:
    size: 1Gi
    storageClass: local-path-ssd
---
kind: Secret
apiVersion: v1
metadata:
  name: pg-arr-users
  namespace: arr
  annotations:
    avp.kubernetes.io/path: "kv/data/arr-pg-users"
type: Opaque
stringData:
  sql: <sql>
