apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cprom-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: charts/kube-prometheus-stack/crds/
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 43.1.1
    syncOptions:
    - Replace=true
    helm:
      releaseName: cprom
      valuesFiles:
      - prom-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cprom
