apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cprom
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 43.1.1
    helm:
      releaseName: cprom
      values:
        prometheus:
          prometheusSpec:    
            storageSpec: 
             volumeClaimTemplate:
               spec:
                 storageClassName: longhorn
                 accessModes: ["ReadWriteOnce"]
                 resources:
                   requests:
                     storage: 25Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cprom
