apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: invidious-db-claim1
  name: invidious-db-claim1
spec:
  storageClassName: local-path-ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
