kind: Secret
apiVersion: v1
metadata:
  name: invidious-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/invidious"
    avp.kubernetes.io/secret-version: "2"
type: Opaque
stringData:
  POSTGRES_DB: <POSTGRES_DB>
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
  POSTGRESS_USER: <POSTGRESS_USER>
  HMAC_KEY: <HMAC_KEY>
