apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgresdata
  name: postgresdata
spec:
  storageClassName: local-path-ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
