---
# Source: nextcloud/templates/nextcloud-secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: paperless-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/paperless"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: <secret>
  PAPERLESS_ADMIN_USER: <user>
  PAPERLESS_ADMIN_PASSWORD: <password>
  PAPERLESS_ADMIN_EMAIL: <email>
