apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.16.2
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/managed-by: Helm
  namespace: authentik
  annotations:
    avp.kubernetes.io/path: "kv/data/authentik-postgresql"
    avp.kubernetes.io/secret-version: "2"
type: Opaque
stringData:
  postgresql-postgres-password: <postgresql-postgres-password>
  postgresql-password: <postgresql-password>
