kind: Secret
apiVersion: v1
metadata:
  name: immich-pg-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/immich-pg"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  username: <user>
  password: <password>
