apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otp-collector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-all-in-one
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traces
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/hostname: jaeger.riles.xyz.
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - jaeger.dev-riles.xyz
    secretName: traces-domain-tls
  rules:
  - host: jaeger.dev-riles.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: jaeger-query
          servicePort: 16686
