apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot
  namespace: zot
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  project: default
  source:
    repoURL: http://zotregistry.io/helm-charts
    chart: project-zot/zot
    helm:
      releaseName: zot
      parameters:
      - name: "service.type"
        value: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zot
