apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot
  namespace: zot
spec:
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  project: default
  source:
    path: "/"
    repoUrl: http://zotregistry.io/helm-charts
    chart: zot
    helm:
      releaseName: zot
      parameters:
      - name: "service.type"
        value: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zot
