kind: Secret
apiVersion: v1
metadata:
  name: harbor-s3-creds
  namespace: harbor
  annotations:
    avp.kubernetes.io/path: "kv/data/harbor"
type: Opaque
stringData:
  VULTR_API_KEY: <
  REGISTRY_STORAGE_S3_ACCESSKEY: <path:kv/data/harbor#minio_secret_id>
  REGISTRY_STORAGE_S3_SECRETKEY: <path:kv/data/harbor#minio_secret_key>

