---
# Source: nextcloud/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-3.5.13
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: app
        release-name-redis-client: "true"
      annotations:
        nextcloud-config-hash: a5aae02b1b8278a9c8a2dc143e82d3737fc295f62c34afd617207f37d1b2b438
        php-config-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:26.0.2-apache
        imagePullPolicy: IfNotPresent
        env:        
        - name: SQLITE_DATABASE
          value: "nextcloud"
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.dev-riles.xyz
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: MAIL_FROM_ADDRESS
          value: "reilly"
        - name: MAIL_DOMAIN
          value: "lefrt.com"
        - name: SMTP_HOST
          value: "lefrt.com"
        - name: SMTP_SECURE
          value: "ssl"
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_AUTHTYPE
          value: "LOGIN"
        - name: SMTP_NAME
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: smtp-password
        - name: REDIS_HOST
          value: release-name-redis-master
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: redis-passwordkey
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status.php
            port:  80
            httpHeaders:
            - name: Host
              value: "nextcloud.dev-riles.xyz"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status.php
            port:  80
            httpHeaders:
            - name: Host
              value: "nextcloud.dev-riles.xyz"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          {}
        volumeMounts:
        - name: nextcloud-main
          mountPath: /var/www/
          subPath: root
        - name: nextcloud-main
          mountPath: /var/www/html
          subPath: html
        - name: nextcloud-main
          mountPath: /var/www/html/data
          subPath: data
        - name: nextcloud-main
          mountPath: /var/www/html/config
          subPath: config
        - name: nextcloud-main
          mountPath: /var/www/html/custom_apps
          subPath: custom_apps
        - name: nextcloud-main
          mountPath: /var/www/tmp
          subPath: tmp
        - name: nextcloud-main
          mountPath: /var/www/html/themes
          subPath: themes
      - name: nextcloud-cron
        image: nextcloud:26.0.2-apache
        imagePullPolicy: IfNotPresent
        command:
        - /cron.sh
        env:        
        - name: SQLITE_DATABASE
          value: "nextcloud"
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: nextcloud-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.dev-riles.xyz
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: MAIL_FROM_ADDRESS
          value: "reilly"
        - name: MAIL_DOMAIN
          value: "lefrt.com"
        - name: SMTP_HOST
          value: "lefrt.com"
        - name: SMTP_SECURE
          value: "ssl"
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_AUTHTYPE
          value: "LOGIN"
        - name: SMTP_NAME
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: smtp-password
        - name: REDIS_HOST
          value: release-name-redis-master
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: redis-passwordkey
        resources:
          {}
        volumeMounts:
        - name: nextcloud-main
          mountPath: /var/www/
          subPath: root
        - name: nextcloud-main
          mountPath: /var/www/html
          subPath: html
        - name: nextcloud-main
          mountPath: /var/www/html/data
          subPath: data
        - name: nextcloud-main
          mountPath: /var/www/html/config
          subPath: config
        - name: nextcloud-main
          mountPath: /var/www/html/custom_apps
          subPath: custom_apps
        - name: nextcloud-main
          mountPath: /var/www/tmp
          subPath: tmp
        - name: nextcloud-main
          mountPath: /var/www/html/themes
          subPath: themes
      volumes:
      - name: nextcloud-main
        nfs:
          path: /tank/nextcloud_nfs
          server: drebin.riles.xyz
      securityContext:
        # Will mount configuration files as www-data (id: 33) for nextcloud
        fsGroup: 33
