kind: Secret
apiVersion: v1
metadata:
  name: basic-auth
  annotations:
    avp.kubernetes.io/path: "kv/data/basic-auth"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  auth: <auth>
