---
# Source: jellyfin/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin
  labels:
    app: jellyfin
data:
  PUID: "65534"
  PGID: "65534"
  TZ: America/New_York
  JELLYFIN_PublishedServerUrl: https://jellyfin.riles.xyz
  NVIDIA_VISIBLE_DEVICES: all
