---
# Source: jellyfin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      hostNetwork: false
      serviceAccountName: jellyfin
      containers:
        - name: jellyfin
          image: "docker.io/linuxserver/jellyfin:10.8.12"
          volumeMounts:
            - mountPath: /data
              name: nfs-data
            - mountPath: /old-data
              name: nfs-data-old
            - mountPath: /config
              name: jf-config
          envFrom:
            - configMapRef:
                name: jellyfin
            - secretRef:
                name: jellyfin
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
      runtimeClassName: nvidia
      volumes:
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: true
        - name: nfs-data-old
          nfs:
            server: drebin.riles.xyz
            path: /home/reilly/transmission
            readOnly: true
        - name: jf-config
          nfs:
            server: drebin.riles.xyz
            path: /ssd_pool/jellyfin_config_dir
