---
# Source: jellyfin/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  labels:
    app: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: jellyfin.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "jellyfin.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jellyfin
              port:
                number: 8096
  tls:
  - hosts:
    - jellyfin.dev-riles.xyz
    secretName: tls-jellyfin-ingress-http
