apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
            - name: TZ
              value: America/New_York
          image: linuxserver/lidarr
          name: lidarr
          ports:
            - containerPort: 8686
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: lidarr-config
            - mountPath: /data
              name: nfs-data
      restartPolicy: Always
      volumes:
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
        - name: lidarr-config
          nfs:
            server: drebin.riles.xyz
            path: /ssd_pool/lidarr-config
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  ports:
    - name: "8686"
      port: 8686
      targetPort: 8686
  selector:
    app: lidarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: lidarr.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: lidarr
spec:
  rules:
  - host: "lidarr.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: lidarr
              port:
                number: 8686
  tls:
  - hosts:
    - lidarr.dev-riles.xyz
    secretName: tls-lidarr-ingress-http
