apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Americas/New_York
          image: linuxserver/prowlarr
          name: prowlarr
          ports:
            - containerPort: 9696
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
      restartPolicy: Always
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  ports:
    - name: "9696"
      port: 9696
      targetPort: 9696
  selector:
    kubernetes.io/name: prowlarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: prowlarr.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "prowlarr.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prowlarr
              port:
                number: 9696
  tls:
  - hosts:
    - prowlarr.dev-riles.xyz
    secretName: tls-prowlarr-ingress-http
