apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-uhd-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr-uhd-pg
  template:
    metadata:
      labels:
        app: radarr-uhd-pg
    spec:
      containers:
        - env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
            - name: TZ
              value: America/New_York
          image: linuxserver/radarr
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp -f /secrets/config.xml /config/config.xml
          name: radarr
          ports:
            - containerPort: 7878
          resources: {}
          volumeMounts:
            - name: radarr-uhd-pg-config-xml
              mountPath: /secrets
            - mountPath: /config
              name: radarr-uhd-pg-config
            - mountPath: /data
              name: nfs-data
            - mountPath: /old-data
              name: nfs-data-old
      restartPolicy: Always
      volumes:
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
        - name: nfs-data-old
          nfs:
            server: drebin.riles.xyz
            path: /home/reilly/transmission
            readOnly: false
        - name: radarr-uhd-pg-config
          emptyDir: {}
        - name: radarr-uhd-pg-config-xml
          secret:
            secretName: radarr-uhd-pg-config
            key: config.xml
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-uhd-pg
spec:
  ports:
    - name: "7878"
      port: 7878
      targetPort: 7878
  selector:
    app: radarr-uhd-pg
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-uhd-pg
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: radarr-uhd-pg.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: radarr-uhd-pg
spec:
  rules:
  - host: "radarr-uhd-pg.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: radarr-uhd-pg
              port:
                number: 7878
  tls:
  - hosts:
    - radarr-uhd-pg.dev-riles.xyz
    secretName: tls-radarr-uhd-pg-ingress-http
---
kind: Secret
apiVersion: v1
metadata:
  name: radarr-uhd-pg-config
  namespace: arr
  annotations:
    avp.kubernetes.io/path: "kv/data/arr-pg-users"
    avp.kubernetes.io/secret-version: "3"
type: Opaque
stringData:
  config.xml: <radarr_uhd_config>
