apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/New_York
          image: linuxserver/radarr
          name: radarr
          ports:
            - containerPort: 7878
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /data
              name: nfs-data
            - mountPath: /old-data
              name: nfs-data-old
      restartPolicy: Always
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
        - name: nfs-data-old
          nfs:
            server: drebin.riles.xyz
            path: /home/reilly/transmission
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
    - name: "7878"
      port: 7878
      targetPort: 7878
  selector:
    app: radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: radarr.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection $http_connection;
       }
spec:
  rules:
  - host: "radarr.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: radarr
              port:
                number: 7878
  tls:
  - hosts:
    - radarr.dev-riles.xyz
    secretName: tls-radarr-ingress-http
