apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-uhd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr-uhd
  template:
    metadata:
      labels:
        app: radarr-uhd
    spec:
      containers:
        - env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
            - name: TZ
              value: America/New_York
          image: linuxserver/radarr
          name: radarr-uhd
          ports:
            - containerPort: 7878
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: radarr-uhd-config
            - mountPath: /data
              name: nfs-data
      restartPolicy: Always
      volumes:
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
        - name: radarr-uhd-config
          nfs:
            server: drebin.riles.xyz
            path: /ssd_pool/radarr-uhd-config
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-uhd
spec:
  ports:
    - name: "7878"
      port: 7878
      targetPort: 7878
  selector:
    app: radarr-uhd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: radarr-uhd.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: radarr
spec:
  rules:
  - host: "radarr-uhd.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: radarr-uhd
              port:
                number: 7878
  tls:
  - hosts:
    - radarr-uhd.dev-riles.xyz
    secretName: tls-radarr-uhd-ingress-http