apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr-pg
  template:
    metadata:
      labels:
        app: readarr-pg
    spec:
      containers:
        - env:
            - name: PGID
              value: "65543"
            - name: PUID
              value: "65543"
            - name: TZ
              value: America/New_York
          image: linuxserver/readarr:develop
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp -f /secrets/config.xml /config/config.xml
          name: readarr
          ports:
            - containerPort: 8787
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: readarr-pg-config
            - name: radarr-pg-config-xml
              mountPath: /secrets
            - mountPath: /data
              name: nfs-data
      restartPolicy: Always
      volumes:
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
        - name: readarr-pg-config
          emptyDir: {}
        - name: readarr-pg-config-xml
          secret:
            secretName: readarr-pg-config
            key: config.xml
---
apiVersion: v1
kind: Service
metadata:
  name: readarr-pg
spec:
  ports:
    - name: "8787"
      port: 8787
      targetPort: 8787
  selector:
    app: readarr-pg
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readarr-pg
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: readarr-pg.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: readarr-pg
spec:
  rules:
  - host: "readarr-pg.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: readarr-pg
              port:
                number: 8787
  tls:
  - hosts:
    - readarr-pg.dev-riles.xyz
    secretName: tls-readarr-pg-ingress-http
---
kind: Secret
apiVersion: v1
metadata:
  name: readarr-pg-config
  namespace: arr
  annotations:
    avp.kubernetes.io/path: "kv/data/arr-pg-users"
    avp.kubernetes.io/secret-version: "2"
type: Opaque
stringData:
  config.xml: <readarr_config>
