kind: Secret
apiVersion: v1
metadata:
  name: transmission-config
  annotations:
    avp.kubernetes.io/path: "kv/data/transmission-config"
    avp.kubernetes.io/secret-version: "5"
type: Opaque
stringData:
  LOCAL_NETWORK: <local_network>
  OPENVPN_CONFIG: <openvpn_config>
  OPENVPN_PASSWORD: <openvpn_password>
  OPENVPN_PROVIDER: <openvpn_provider>
  OPENVPN_USERNAME: <openvpn_username>
  TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: <rpc_auth_enable>
  TRANSMISSION_RPC_ENABLED: <rpc_enable>
  TRANSMISSION_RPC_PASSWORD: <rpc_pw>
  TRANSMISSION_RPC_USERNAME: <rpc_user>
