kind: Secret
apiVersion: v1
metadata:
  name: transmission-config
  namespace: transmission
  annotations:
    avp.kubernetes.io/path: "kv/data/transmission-config"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  LOCAL_NETWORK: <local_network>
  OPENVPN_CONFIG: <openvpn_config>
  OPENVPN_PASSWORD: <openvpn_password>
  OPENVPN_PROVIDER: <openvpn_provider>
  OPENVPN_USERNAME: <openvpn_username>
