apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
            - name: TZ
              value: America/New_York
          image: linuxserver/sonarr
          name: sonarr
          ports:
            - containerPort: 8989
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: sonarr-config
            - mountPath: /data
              name: nfs-data
            - mountPath: /old-data
              name: nfs-data-old
      restartPolicy: Always
      volumes:
        - name: nfs-data-old
          nfs:
            server: drebin.riles.xyz
            path: /home/reilly/transmission
            readOnly: false
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
        - name: sonarr-config
          nfs:
            server: drebin.riles.xyz
            path: /ssd_pool/sonarr-config
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8989
  selector:
    app: sonarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: sonarr.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "sonarr.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sonarr
              port:
                number: 8989
  tls:
  - hosts:
    - sonarr.dev-riles.xyz
    secretName: tls-sonarr-ingress-http
