apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-pg
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr-pg
  template:
    metadata:
      labels:
        app: sonarr-pg
    spec:
      containers:
        - env:
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
            - name: TZ
              value: America/New_York
          image: linuxserver/sonarr
          name: sonarr
          ports:
            - containerPort: 8989
          resources: {}
          volumeMounts:
            - name: sonarr-pg-config-xml
              mountPath: "/config/config.xml"
            - mountPath: /config
              name: sonarr-pg-config
      restartPolicy: Always
      volumes:
        - name: sonarr-pg-config
          persistentVolumeClaim:
            claimName: sonarr-pg-config-pvc
        - name: sonarr-pg-config-xml
          secret:
            secretName: sonarr-pg-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pg-config-pvc
  namespace: arr
spec:
  storageClassName: local-path-ssd
  volumeName: sonarr-pg-config-pv
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-pg
spec:
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8989
  selector:
    app: sonarr-pg
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-pg
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: sonarr-pg.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: sonarr-pg
spec:
  rules:
  - host: "sonarr-pg.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sonarr-pg
              port:
                number: 8989
  tls:
  - hosts:
    - sonarr-pg.dev-riles.xyz
    secretName: tls-sonarr-pg-ingress-http
---
kind: Secret
apiVersion: v1
metadata:
  name: sonarr-pg-config
  namespace: arr
  annotations:
    avp.kubernetes.io/path: "kv/data/sonarr-pg"
type: Opaque
stringData:
  config.xml: <config>
