apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-openvpn
  template:
    metadata:
      labels:
        app: transmission-openvpn
    spec:
      containers:
        - envFrom:
          secretRef:
            name: transmission-config
          image: haugene/transmission-openvpn
          name: transmission-openvpn
          ports:
            - containerPort: 9091
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /config
              name: transmission-openvpn-config
            - mountPath: /data
              name: nfs-data
      restartPolicy: Always
      volumes:
        - name: transmission-openvpn-config
          persistentVolumeClaim:
            claimName: transmission-openvpn-config
        - name: nfs-data
          nfs:
            server: drebin.riles.xyz
            path: /tank/transmission_k8s_data
            readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-openvpn-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-openvpn
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    app: transmission-openvpn
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-openvpn
  annotations:
    cert-manager.io/cluster-issuer: le-example-http
    external-dns.alpha.kubernetes.io/hostname: transmission-openvpn.dev-riles.xyz.
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "transmission-openvpn.dev-riles.xyz"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: transmission-openvpn
              port:
                number: 9696
  tls:
  - hosts:
    - transmission-openvpn.dev-riles.xyz
    secretName: tls-transmission-openvpn-ingress-http
