apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  destination:
    namespace: alert
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: alertmanager
    plugin:
      env:
      - name: HELM_VALUES
        value: |
          config:
            enabled: true
            global:
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: ops@riles.xyz
            receivers:
              - name: reilly
                email_configs:
                  - to: reilly@lefrt.com
                    send_resolved: true
                    auth_username: <path:kv/data/authentik#smtp_username>
                    auth_password: <path:kv/data/authentik#smtp_app_pw>
            route:
              receiver: reilly
          ingress:
            enabled: true
            hosts:
              - host: alertmanager.dev-riles.xyz
                paths:
                  - path: /
                    pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: le-example-http
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
            tls:
              - secretName: vm-tls
                hosts:
                  - alertmanager.dev-riles.xyz
          configmapReload:
            enabled: true
      name: argocd-vault-plugin-helm
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 1.7.0
