apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr
  namespace: argocd
spec:
  destination:
    namespace: arr
    server: https://kubernetes.default.svc
  project: media
  source:
    path: transmission-openvpn
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
