apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg
    directory:
      include: releases/cnpg-1.23.1.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
