apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: external-dns
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
