apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  project: office
  source:
    helm:
      values: |
        env:
          TZ: America/Toronto
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: homepage.dev-riles.xyz
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: homepage-tls
                hosts:
                  - homepage.dev-riles.xyz
            annotations:
              cert-manager.io/cluster-issuer: le-example-http
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
    repoURL: oci://ghcr.io/oben01/charts
    targetRevision: 2.0.2 
    chart: dashdot
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
