apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        controller:
          metrics:
            enabled: true
          ingressClassResource:
            default: true
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
