apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-metrics
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  project: office
  source:
    path: nextcloud-metrics
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
