apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: opensearch
    helm:
      values: |
        singleNode: true
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 2.15.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
