apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  destination:
    namespace: paperless
    server: https://kubernetes.default.svc
  project: office
  source:
    path: paperless
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
