apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest
  namespace: argocd
spec:
  destination:
    namespace: speedtest
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: speedtest-exporter
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
