apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vultr-certmanager-webhook-secret
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vultr-certmanager-webhook-secret
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
