apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vultr-webhook
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vultr-certmanager-webhook
    repoURL: https://github.com/riles-m/argocd-definitions
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
