kind: Secret
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: photoprism
    helm.sh/chart: photoprism-1.3.1
    app.kubernetes.io/instance: photoprism
    app.kubernetes.io/version: "20211215"
    app.kubernetes.io/managed-by: Helm
  name: photoprism-secret
  namespace: productivity
  annotations:
    avp.kubernetes.io/path: "kv/data/photoprism"
    avp.kubernetes.io/secret-version: "3"
type: Opaque
stringData:
  PHOTOPRISM_DATABASE_DSN: <db_path>
  PHOTOPRISM_ADMIN_PASSWORD: <db_admin_pw>
  PHOTOPRISM_ADMIN_USER: <admin_user>
  PHOTOPRISM_ADMIN_PW: <admin_pw>
  PHOTOPRISM_AUTH_MODE: <auth_mode>
