kind: Secret
apiVersion: v1
metadata:
  name: vultr-secrets
  namespace: external-dns
  annotations:
    avp.kubernetes.io/path: "kv/data/vultr"
type: Opaque
stringData:
  VULTR_API_KEY: <vultr_api_key>
