apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: le-example-http
 namespace: cert-manager
spec:
 acme:
   email: reilly@lefrt.com
   # We use the staging server here for testing to avoid hitting
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: le-issuer-account-key
   solvers:
   - dns01:
       webhook:
         groupName: acme.vultr.com
         solverName: vultr
         config:
           apiKeySecretRef:
             key: apiKey
             name: vultr-credentials
           # The ingressClass used to create the necessary ingress routes
           ingress:
             class: traefik
